# Source: cluster-api-aws/templates/job-check.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: 6ee85d2d-49bd-4095-bcdf-8d145382759a-capi-aws-check
  namespace: 6ee85d2d-49bd-4095-bcdf-8d145382759a
spec:
  template:
    metadata:
      name: 6ee85d2d-49bd-4095-bcdf-8d145382759a-capi-aws
    spec:
      serviceAccountName: 6ee85d2d-49bd-4095-bcdf-8d145382759a-capi-aws
      containers:
      - name: wait-for-ready
        image: "ghcr.io/openinfradev/python_kubectl_argo:v1.1.0"
        imagePullPolicy: IfNotPresent
        command:
        - timeout 
        - 5m
        - /wait_for_kubeconfig.sh  
        - 6ee85d2d-49bd-4095-bcdf-8d145382759a
        - 6ee85d2d-49bd-4095-bcdf-8d145382759a
        volumeMounts:
        - name: vol
          subPath: wait_for_kubeconfig.sh
          mountPath: /wait_for_kubeconfig.sh
      volumes:
      - name: vol
        configMap:
          name: 6ee85d2d-49bd-4095-bcdf-8d145382759a-capi-aws
          defaultMode: 0555
      restartPolicy: OnFailure
